set_property -dict {PACKAGE_PIN AF25 IOSTANDARD LVCMOS33} [get_ports {buzzer}]
set_property -dict {PACKAGE_PIN AC18 IOSTANDARD LVCMOS18} [get_ports {clk}]
set_property -dict {PACKAGE_PIN P26 IOSTANDARD LVCMOS33} [get_ports {AUD_PWM}]
set_property -dict {PACKAGE_PIN M25 IOSTANDARD LVCMOS33} [get_ports {AUD_SD}]
set_property -dict {PACKAGE_PIN AA10  IOSTANDARD LVCMOS15} [get_ports {switch}]
set_property -dict {PACKAGE_PIN AB10  IOSTANDARD LVCMOS15} [get_ports {switch2}]